### ISSUE TITLE
connect problem

### ISSUE THREAD

**Issue by andy6804tw** [song940/node-bluetooth#20]
Hi this is my error message. how can I solve it? thx!

```
Found RFCOMM channel for serial port on BRA-801:  1
2018-11-09 21:40:56.290 node[2668:117275] instantiateOnDevice for regular
/Users/ca/Desktop/bluetooth/node_modules/node-bluetooth/lib/connection.js:9
    const self = this;
                 ^

ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new Connection (/Users/cai/Desktop/bluetooth/node_modules/node-bluetooth/lib/connection.js:9:18)
    at /Users/cai/Desktop/bluetooth/node_modules/node-bluetooth/index.js:18:33
```

**Comment by daksen** [comment]
I also have the same problem :/

**Comment by song940** [comment]
What's version of module and node ?

**Comment by andy6804tw** [comment]
@song940  v9.11.1

**Comment by daksen** [comment]
@andy6804tw v10.13.0

**Comment by song940** [comment]
Upgrade node-bluetooth to latest version.

**Comment by andy6804tw** [comment]
@song940 same problem. @daksen  and you?

**Comment by song940** [comment]
@andy6804tw pls copy your "lib/connection.js" file and paste  here .

```bash
cat /Users/ca/Desktop/bluetooth/node_modules/node-bluetooth/lib/connection.js | pbcopy
```

**Comment by andy6804tw** [comment]
@song940 

```js
const EventEmitter = require('events');

/**
 * [function description]
 * @return {[type]} [description]
 */
class Connection extends EventEmitter {
  constructor(port, address) {
    const self = this;
    this.port = port;
    this.address = address;
    this.buffer = Buffer.alloc(0);
    const read = function () {
      process.nextTick(function () {
        if (self.isOpen()) {
          self.port.read(function (err, chunk) {
            if (err) return self.emit('error', err);
            if (self.delimiter) {
              let data = Buffer.concat([self.buffer, chunk]);
              let position;
              while ((position = data.indexOf(self.delimiter)) !== -1) {
                self.emit('data', data.slice(0, position));
                data = data.slice(position + self.delimiter.length);
              }
              self.buffer = data;
            } else {
              self.emit('data', chunk);
            }
            read();
          });
        }
      });
    }
    read();
  }
  /**
   * [write description]
   * @param  {[type]}   data     [description]
   * @param  {Function} callback [description]
   * @return {[type]}            [description]
   */
  write(data, callback){
    this.port.write(data, this.address, callback);
    return this;
  }
  /**
   * [close description]
   * @param  {Function} callback [description]
   * @return {[type]}            [description]
   */
  close(){
    try {
      this.port.close(this.address);
      this.port = undefined;
      callback && callback();
    } catch (e) {
      callback && callback(e);
    }
    return this;
  }
  isOpen(){
    return this.port !== undefined;
  }
}


module.exports = Connection;
```

**Comment by song940** [comment]
fixed, pls install latest version

```bash
npm i  node-bluetooth@1.2.4
```

**Comment by andy6804tw** [comment]
@song940 Thank you for your help! But the device is not with me. I am testing the day after tomorrow.

**Comment by song940** [comment]
Any questions?
