### ISSUE TITLE
Installation Python and Gyp Error

### ISSUE THREAD

**Issue by rolecram** [song940/node-bluetooth#29]
I have python-3.7.2-amd64 and node-gyp installed (global), when I try to install the module with:
npm install node-bluetooth --save

I receive the following errors:

C:\Projects\BluetoothServer\node_modules\node-bluetooth>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
**gyp ERR! configure error**
**gyp ERR! stack Error: Command failed:** **C:\Users\Marcelo\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax**
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Projects\BluetoothServer\node_modules\node-bluetooth
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Projects\BluetoothServer\package.json'
npm WARN BluetoothServer No description
npm WARN BluetoothServer No repository field.
npm WARN BluetoothServer No README data
npm WARN BluetoothServer No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.5 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcelo\AppData\Roaming\npm-cache\_logs\2019-03-08T20_35_51_000Z-debug.log

C:\Projects\BluetoothServer>path
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Acer ProShield\;C:\Program Files\Acer ProShield\x86;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Amazon\AWSCLI\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Users\Marcelo\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Marcelo\AppData\Local\Programs\Python\Python37\;C:\Users\Marcelo\AppData\Local\Microsoft\WindowsApps;C:\Users\Marcelo\AppData\Roaming\npm

C:\Projects\BluetoothServer>
C:\Projects\BluetoothServer>npm i node-bluetooth

> node-bluetooth@1.2.5 install C:\Projects\BluetoothServer\node_modules\node-bluetooth
> node-gyp configure build

C:\Projects\BluetoothServer\node_modules\node-bluetooth>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Marcelo\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Projects\BluetoothServer\node_modules\node-bluetooth
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Projects\BluetoothServer\package.json'
npm WARN BluetoothServer No description
npm WARN BluetoothServer No repository field.
npm WARN BluetoothServer No README data
npm WARN BluetoothServer No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.5 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcelo\AppData\Roaming\npm-cache\_logs\2019-03-08T20_41_44_146Z-debug.log

**Comment by readeral** [comment]
You might need to be using Python 2.7. See the node-gyp package here: https://github.com/nodejs/node-gyp
although it refers to Python 2.7 in only the Mac and Unix sections - there might be specific requirements you haven't met in the PC section, or your version of Python won't work.
