### ISSUE TITLE
ChannelId -1

### ISSUE THREAD

**Issue by Attacler** [song940/node-bluetooth#34]
Hello there,

Whenever i try to run the example, this error comes up:
/home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18
    const port = new BTSerialPortBinding(address, channel, function (err) {
                 ^

TypeError: ChannelID should be a positive int value.
    at Function.connect (/home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18:18)
    at /home/pi/node-bluetooth/script.js:17:15

How can i solve this?

Greetings,
Bart

**Comment by Puneetkumarpal** [comment]
i have same issue can any one help and there is any way to run any bluetooth api in electron no api is work in a proper way may be it's my implementation or there is no api for electron plz help is any can


thanks

**Comment by VasilisCh** [comment]
> Hello there,
> 
> Whenever i try to run the example, this error comes up:
> /home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18
> const port = new BTSerialPortBinding(address, channel, function (err) {
> ^
> 
> TypeError: ChannelID should be a positive int value.
> at Function.connect (/home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18:18)
> at /home/pi/node-bluetooth/script.js:17:15
> 
> How can i solve this?
> 
> Greetings,
> Bart

Did you find any solution? I try to execute it on raspberry pi 3 b+.

Thanks,
bill

**Comment by Attacler** [comment]
> > Hello there,
> > Whenever i try to run the example, this error comes up:
> > /home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18
> > const port = new BTSerialPortBinding(address, channel, function (err) {
> > ^
> > TypeError: ChannelID should be a positive int value.
> > at Function.connect (/home/pi/node-bluetooth/node_modules/node-bluetooth/index.js:18:18)
> > at /home/pi/node-bluetooth/script.js:17:15
> > How can i solve this?
> > Greetings,
> > Bart
> 
> Did you find any solution? I try to execute it on raspberry pi 3 b+.
> 
> Thanks,
> bill

Hey Bill,

I did not find a solution yet...
I moved on to another project and will continue the bluetooth one when its fixed.

Greetings,
Bart

**Comment by pedrohb88** [comment]
Any solution on this issue?

**Comment by VasilisCh** [comment]
@pedrohb88

for me the solution was to move to python. Took about an hour to achieve connection, between the raspberry and my phone.

Greetings,
bill

**Comment by asifma** [comment]
Have the same problem here, anyone solved it with -1 in channelid?

**Comment by sujitpatil72** [comment]
Did anyone find any solution?
