### ISSUE TITLE
Error: The connection has been closed

### ISSUE THREAD

**Issue by naxiemolv** [song940/node-bluetooth#35]
Thank First

code in example  works with Elelctron, but when I shutdown my bluetooth device, it repeats like..........

```
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: The connection has been closed
    at read (/Users/project/node_modules/node-bluetooth/lib/connection.js:14:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by song940** [comment]
Handle the `connection.on("error")` events and  call `connection.close()` method. 

```js
connection.on("error", err => {
  connection.close();
});
```
