### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by mdsaddam** [song940/node-bluetooth#45]
Working on an Electron JS app for linux.
Followed the installation process given in about page, getting following errors while installing the package unable to proceed further.

```
> node-bluetooth@1.2.6 install /home/user/Documents/electronjs/bluetooth_test/node_modules/node-bluetooth
> node-gyp configure build

make: Entering directory '/home/user/Documents/electronjs/bluetooth_test/node_modules/node-bluetooth/build'
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void
 void InitAll(Handle<Object> exports) {
              ^
../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in this scope
../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token
 void InitAll(Handle<Object> exports) {
                           ^
../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in this scope
 void InitAll(Handle<Object> exports) {
                             ^
In file included from ../src/linux/BluetoothSerialPort.cc:12:0:
../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in this scope
 NODE_MODULE(BluetoothSerialPort, InitAll)
                                  ^
/home/user/.cache/node-gyp/12.8.1/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^
../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(BluetoothSerialPort, InitAll)
 ^
BluetoothSerialPort.target.mk:115: recipe for target 'Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o' failed
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o] Error 1
make: Leaving directory '/home/user/Documents/electronjs/bluetooth_test/node_modules/node-bluetooth/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/user/.nvm/versions/node/v12.8.1/bin/node" "/home/user/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/user/Documents/electronjs/bluetooth_test/node_modules/node-bluetooth
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN bluetooth_test@1.0.0 No description
npm WARN bluetooth_test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-bluetooth@1.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

OS - Ubuntu 16.04
Node - 12.8.1
NPM - 6.10.2
Electron JS - 7.0.1
Node-gyp - 5.0.3

**Comment by manish-impressico** [comment]
Facing exactly same issue in Ubuntu 18 . Need help.

**Comment by frankjoke** [comment]
@mdsaddam,
can you create a fork of the project which includes your upstream changes?
The problem is that your copy solution does not work on any of my systems. 
I could install your latest bluetooth-serial-port but it is not helping because even if I try to install this git repo it tries to copy it from somehere where it could not find it.

**Comment by nikhilism15** [comment]
I'm facing the same issue. I am not sure what I am doing wrong, anyone has any idea?
