### ISSUE TITLE
Can't install in Windows

### ISSUE THREAD

**Issue by christophervistal25** [song940/node-bluetooth#46]
I've already installed the node-gyp
then try to run npm install node-bluetooth --save
but I got this error.

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\MonstaX\Downloads\Compressed\node-bluetooth-master
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.6 install: `prebuild-install || node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MonstaX\AppData\Roaming\npm-cache\_logs\2019-11-13T11_24_01_389Z-debug.log
```

**Comment by tazougphi** [comment]
Are you using Visual Studio 2019? I was having the same issue, installing Visual Studio 2017 fixed it

edit: I also had to downgrade to NodeJS 11

**Comment by christophervistal25** [comment]
I will try your recommendation thank you so much.

**Comment by gnesher** [comment]
Does not fix the problem for me, anyone else experiencing this?

**Comment by FJKMAN** [comment]
Can't install I have VS2017 installed
