### ISSUE TITLE
Cant install On windows

### ISSUE THREAD

**Issue by MaroueneKh** [song940/node-bluetooth#52]
I've installed node-gyp succesfuly but when installing node-bluetooth this is the following output : 
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\marou\Documents\OSC\Node\node_modules\node-bluetooth
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marou\AppData\Roaming\npm-cache\_logs\2020-09-09T10_17_15_477Z-debug.log

**Comment by keitetran** [comment]
same here 
```

\node_modules\node-bluetooth\src\windows\deviceinq.cc(522): error C2660: 'v8::Function::Call': function does not take 3 arguments [\node_modules\node-bluetooth\build\BluetoothSerialPort.vcxproj]
```

**Comment by arjun1194** [comment]
I am having same issues on Apple silicon

**Comment by Liting1** [comment]
I ran into this problem on Windows 10 as well

**Comment by timwhite06** [comment]
any updates on this?
